### PR TITLE
update netCDF-Java libs

### PR DESCRIPTION
**Pull request by lesserwhirls**

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
I updated my `pom.xml` to use this one, and now I don't get the dependency errors.  Woohoo!
I do get the following failed test, however.  Any ideas?
```
Results :

Failed tests:   htmlReadTest(gov.noaa.eds.threddsutilities.util.XMLUtilTest)

Tests in error:
  translateTest(gov.noaa.eds.threddsutilities.util.ThreddsTranslatorUtilTest): Configuration problem: http://www.ngdc.noaa.gov/metadata/published/xsl/UnidataDDCount-HTML.xsl TransformerConfigurationException. javax.xml.transform.TransformerException: org.xml.sax.SAXParseException; systemId: http://www.ngdc.noaa.gov/metadata/published/xsl/UnidataDDCount-HTML.xsl; lineNumber: 1; columnNumber: 50; White spaces are required between publicId and systemId.

Tests run: 5, Failures: 1, Errors: 1, Skipped: 0
```

**Comment by rsignell-usgs** [comment]
@geoneubie, there must be another `http:` sneaking around somewhere, right?
I got the above error using the 2 changes to `https:` you suggested here: https://github.com/noaaroland/uafnciso/pull/1/files

**Comment by geoneubie** [comment]
These tests look pretty brittle...

But yea here:
https://github.com/noaaroland/uafnciso/blob/master/src/test/java/gov/noaa/eds/threddsutilities/util/ThreddsTranslatorUtilTest.java#L11

And then there's a hardcoded path below here that you might update to /tmp
https://github.com/noaaroland/uafnciso/blob/master/src/test/java/gov/noaa/eds/threddsutilities/util/ThreddsTranslatorUtilTest.java#L16

**Comment by rsignell-usgs** [comment]
@noaaroland , does this repo actually build successfully for you?

**Comment by noaaroland** [comment]
Yes, @rsignell-usgs of course it builds.

Once I commit my local changes that it. Anyhoo, I updated the pom and made a release of a jar that you should try.

**Pull request closed without merging**
